config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
   # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 
  get 'posts/index'
  
  
  
  get 'users/:id/edit_profile', to: 'users#edit_profile', as: :users_profile # プロフィール設定画面
  patch 'users/:id/update_profile', to: 'users#update_profile', as: :update_profile # プロフィール アップデート
  get 'users/:id/edit_mypage', to: 'users#edit_mypage', as: :edit_mypage # マイページ
  patch 'users/:id/update_mypage', to: 'users#update_mypage', as: :update_mypage # マイページ アップデート
  patch 'users/:id/upload_instagram', to: 'users#upload_instagram', as: :upload_instagram # instagram アップロード
  get 'users/:id/edit_picture', to: 'users#edit_picture', as: :edit_picture # 画像編集
  patch 'users/:id/update_picture', to: 'users#update_picture', as: :update_picture # 画像アップロード
  delete 'users/:id/withdraw', to: 'users#withdraw', as: :withdraw # 退会処理
  
  
  get 'users/:id/posts/:post_id/users_confirm_posts', to: 'posts#users_confirm_posts', as: :confirm_posts #　userの記事を確認するページ
  get 'users/:id/posts/:post_id/users_edit_posts', to: 'posts#users_edit_posts', as: :edit_posts #　記事を編集するページ
  patch 'users/:id/posts/:post_id/users_update_posts', to: 'posts#users_update_posts', as: :update_posts #　記事を更新
  delete 'users/:id/posts/:post_id/users_delete_posts', to: 'posts#users_destroy_posts', as: :delete_posts #　記事を削除
  
  resources :users do
     
    get 'posts/:id/posts_show', to: 'posts#posts_show', as: :posts_show # モーダルウィンドウ
    get 'posts/users_posts', to: 'posts#users_posts', as: :posts #　記事を投稿するページ
    post 'posts/users_create_posts', to: 'posts#users_create_posts', as: :create_posts #　記事を作る
    
    
    get 'urls/add_mypage_content', to: 'urls#add_mypage_content', as: :add_mypage_content # マイページへ写真、動画をアップロードする為のページ
    post 'urls/add_mypage_content_create', to: 'urls#add_mypage_content_create', as: :add_mypage_content_create # マイページへ写真、動画をアップロードする
    
    patch 'urls/:id/users_imaeg_and_video_url', to: 'urls#users_imaeg_and_video_url', as: :users_url
    
    post 'favorite_folders/:id/create', to: 'favorite_folders#create', as: :create
    delete 'favorite_folders/:id/delete', to: 'favorite_folders#destroy', as: :destroy
  end
  
  delete 'rooms/:id/messages/:message_id/message_delete', to: 'messages#destroy', as: :message_delete
  
  resources :messages, only: [:create] do
  end
  
  resources :rooms, only: [:create, :show, :index] do
  end
  
 
end

app/models/user.rb
class User < ApplicationRecord
  
  mount_uploader :image, ImageUploader
  
  has_many :posts, dependent: :destroy
  has_many :urls, dependent: :destroy
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :footprints, dependent: :destroy
  has_many :favorite_folders, class_name: 'FavoriteFolder', dependent: :destroy
  
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, on: :create, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true    
  has_secure_password
  validates :password, presence: true, on: :create, length: { minimum: 6 }
  
  
  validates :prefecture, presence: true, on: :update_profile
  validates :responsible_part, presence: true, on: :update_profile
  validates :age, presence: true, on: :update_profile
  validates :sex, presence: true, on: :update_profile
  validates :self_introduction, length: { maximum: 15000 }, presence: true, on: :update_profile
  validates :genre, presence: true, on: :update_profile
  
  validates :first_token, presence: true, on: :upload_instagram
  validates :app_id, presence: true, on: :upload_instagram
  validates :app_secret, presence: true, on: :upload_instagram
  validates :media_count, presence: true, on: :upload_instagram
 
 
  
  enum prefecture:{
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
     沖縄県:47
   }
   
   enum responsible_part: {
     
     ボーカル:1,ギター:2,ベース:3,ピアノ・キーボード:4,ドラム:5,パーカッション:6,
     管楽器:7,弦楽器:8,作詞作曲・アレンシャー:9,DJ:10,ダンサー:11,その他:12
   }
   
   enum genre: {
     ポップス:1,ロック:2,ハードロック・ヘヴィメタル:3,パンク・メロコア:4,ハードコア:5,スラッシュメタル・デスメタル:6,
     ビジュアル系:7,ファンク・ブルース:8,ジャズ・フュージョン:9,カントリー・フォーク:10,スカ・ロカビリー:11,ソウル:12,
     ゴスペル・アカペラ:13,ボサノバ・ラテン:14,クラシック:15,ヒップホップ・レゲエ:16,ハウス・テクノ:17,アニソン・ボカロ:18,
     他:19
   }
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  before_action :set_user, only: [:show, :edit_profile, :update_profile, :edit_mypage, :update_mypage, :edit_picture, :update_picture, :upload_instagram, :destroy]
  before_action :set_instagram_create, only: [:edit_mypage]
  before_action :create_footprint, only: [:edit_mypage]
  before_action :user_profile_set, only: [:edit_mypage]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    @user.update(image: File.open("./public/user_images/default.png"))
    if @user.save
      log_in @user # 保存成功後、ログインします。
      flash[:success] = '新規作成に成功しました。'
      redirect_to users_profile_url(@user)
    else
      render :new
    end
  end
  
  def index
    @users = User.paginate(page: params[:page], per_page: 20)
  end
  
  def edit_profile
    
  end
 
  def update_profile
      @user.attributes = { name: user_params[:name], age: user_params[:age], sex: user_params[:sex], purpose_of_use: user_params[:purpose_of_use], 
                           prefecture: user_params[:prefecture], responsible_part: user_params[:responsible_part], genre: user_params[:genre],
                           favorite_artist: user_params[:favorite_artist], self_introduction: user_params[:self_introduction]}
      if @user.save(context: :update_profile)
        flash[:success] = "ユーザー情報を更新しました。"
        redirect_to edit_mypage_url(current_user)
      else
        render :edit_profile
      end
  end
  
  def edit_mypage
    @url = Url.new
    @unread_counts = current_user.messages.where(already_read: "未読").count
    # メッセージルームのidを作成
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    # 足跡機能
    @footprints = Footprint.all.where(visited_id: @user.id).pluck(:visiter_id)
    # お気に入り機能
    @favorite = FavoriteFolder.new
    @favorite_users_id = current_user.favorite_folders.pluck(:favorite_user)
    
      
  
    
    if @user.id == current_user.id
      # 今までやりとりしたuserを全て表示する
      if current_user.entries.where(user_id: current_user.id).present?
        @room_ids = current_user.entries.pluck(:room_id) # 現在ログインしているユーザーが持っているroom_idを取得
        
          @users = Entry.where(room_id: @room_ids).where.not(user_id: current_user.id) # 現在ログイン中のユーザーが持っているroom_idと同じidを持っているユーザーを表示
         
        
      end
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
     
      else   # やりとりしたことがないuserだった場合room_idが初めて作られる。
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
  
  def update_mypage
   
  end
  #　インスタグラムのデータを取り込む
  def upload_instagram
    
  
     @user.attributes = { first_token: instagram_params[:first_token], second_token: instagram_params[:second_token], third_token: instagram_params[:third_token], app_id: instagram_params[:app_id], 
                          app_secret: instagram_params[:app_secret], media_count: instagram_params[:media_count]}
    if @user.save(context: :upload_instagram)
      token = @user.first_token
      app_id = @user.app_id
      app_secret = @user.app_secret
       # media_count = @user.media_count
    else
      flash[:danger] = "入力項目が不足しています。"
      render :edit_mypage and return
    end
      res = Net::HTTP.get(URI.parse("https://graph.facebook.com/v3.0/oauth/access_token?grant_type=fb_exchange_token&client_id=#{app_id}&client_secret=#{app_secret}&fb_exchange_token=#{token}"))
      if JSON.parse(res)["access_token"].nil?
        flash[:danger] = "入力情報が正しくありません。"
        render :edit_mypage
      else
        # second_token取得
        second = JSON.parse(res)["access_token"]
        id = Net::HTTP.get(URI.parse("https://graph.facebook.com/v5.0/me?access_token=#{second}"))
        id = JSON.parse(id)["id"]
        third = Net::HTTP.get(URI.parse("https://graph.facebook.com/v5.0/#{id}/accounts?access_token=#{second}"))
        third = JSON.parse(third)
        
        # third_token取得
        @user[:third_token] = third["data"][0]["access_token"]
        @user.save
        
        flash[:info] = "instagramから画像と動画を取り込むためのデータを入力しました。"
        flash[:danger] = "コンテンツが表示されない場合は入力情報を確認してください。"
        redirect_to edit_mypage_url
      end
  
  
  end
   
  def edit_picture
    
  end
  
  def update_picture
    if  @user.update(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to users_profile_url
    else
      flash[:danger] = "更新できませんでした。"
      render :edit_profile
    end
  end
  
  def destroy
    @user.destroy
    flash[:info] = "ユーザーを削除しました。"
    redirect_to users_url
  end
  
  def withdraw
    unless current_user.admin?
      current_user.destroy
      flash[:info] = "退会しました。"
      redirect_to root_url
    else
      flash[:danger] = "管理ユーザーは削除できません。"
      redirect_to root_url
    end
  end
  
  private
  
  def set_user
   @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :image, :password, :password_confirmation, :age, :sex, :purpose_of_use, :prefecture, :responsible_part, :genre, :favorite_artist, :self_introduction)
  end
  
  def instagram_params
    params.require(:user).permit(:first_token, :second_token, :third_token, :app_id, :app_secret, :media_count)
  end
  # もし第３トークンを持っているユーザーなら、インスタの画像、動画データをUrlモデルのusers_urlカラムに格納します。
  def set_instagram_create
    if @user.third_token.present? && !@user.urls.where.not(users_url: nil).present? # users_urlに値が入っているidのデータが存在していなくて、第３トークンが存在している時
      third = @user.third_token                         # ↑ここがネック
      media_count = @user.media_count
   
      instagram_business_account = Net::HTTP.get(URI.parse("https://graph.facebook.com/v6.0/me?fields=instagram_business_account&access_token=#{third}"))
      instagram_business_account = JSON.parse(instagram_business_account)["instagram_business_account"]["id"]
        
        
      user_media = Net::HTTP.get(URI.parse("https://graph.facebook.com/v3.3/#{instagram_business_account}?fields=name%2Cmedia.limit(#{media_count})%7Bcaption%2Clike_count%2Cmedia_url%2Cpermalink%2Ctimestamp%2Cusername%7D&access_token=#{third}"))
      res = JSON.parse(user_media) 
      res["media"]["data"].each { |insta| @user.urls.create(users_url: insta["media_url"]) }
      
      @instagram = @user.urls.where.not(id: nil) 
    elsif @user.third_token.present? && @user.urls.present?
      @instagram = @user.urls.where.not(id: nil)
    end
  end
  
  def footprint_params
    params.require(:footprint).permit(:visiter_id, :visited_id)
  end
    
  
  def create_footprint
    @user = User.find(params[:id])
    unless (current_user == @user)
      unless current_user.footprints.where(visited_id: @user.id).present?
        @footprint = Footprint.new(user_id: current_user.id, visiter_id: current_user.id, visited_id: @user.id)
        @footprint.save
      end
    end
  end
  
  def user_profile_set
    unless current_user.age.present? && current_user.sex.present? && current_user.self_introduction.present?
      flash[:info] = "プロフィールを設定してください。"
      redirect_to users_profile_url
    end
  end
 
end

app/helpers/users_helper.rb
module UsersHelper
  require 'net/http' #標準ライブラリの呼び出し
  require 'uri'
  require "json" #jsonを使うためのライブラリ

 def instagram
  if @user.third_token.present?
   third = @user.third_token
   media_count = @user.media_count
   
   instagram_business_account = Net::HTTP.get(URI.parse("https://graph.facebook.com/v6.0/me?fields=instagram_business_account&access_token=#{third}"))
   instagram_business_account = JSON.parse(instagram_business_account)["instagram_business_account"]["id"]
    
    
   user_media = Net::HTTP.get(URI.parse("https://graph.facebook.com/v3.3/#{instagram_business_account}?fields=name%2Cmedia.limit(#{media_count})%7Bcaption%2Clike_count%2Cmedia_url%2Cpermalink%2Ctimestamp%2Cusername%7D&access_token=#{third}"))
   JSON.parse(user_media)
  end
 end
 
end

app/views/users/edit_mypage.html.erb
<div class="container">
<div class="comment">
  <div class="comment-left">
    <div class="user-image"><%= image_tag @user.image, :size => '230x230' %></div>
  </div>
  <div class="comment-right">
    <h1 class="user-name-mypage"><%= @user.name %><span class="user-info">(<%= @user.prefecture %>,<%= @user.age %>歳,<%= @user.sex %>)</span></h1>
    <ul class="test">
      <li>担当パート:<%= @user.responsible_part %></li>
      <li>好きなジャンル:<%= @user.genre %></li>
      <li>好きなアーティスト:<%= @user.favorite_artist %></li>
    </ul>
    <ul class="test">
      <li class="self-introduction"><%= @user.self_introduction %></li>
    </ul>
  </div>
  
  
  
  
  <div class="menu">
  
  
  <div class="menu-list">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <div>from-instagram</div>
      </a>
      <ul class="dropdown-menu">
        <li>      
        <% if @user.id == current_user.id %> <!-- ログイン中のユーザーだった場合  -->
        <h2>マイページにinstagramの写真、動画を追加します。</h2><hr>
        <!-- マイページにinstagramの写真、動画を追加する -->
        <%= form_with(model: @user, url: upload_instagram_path, method: :patch, local: true) do |f| %>
        
          <%= f.label :token, class: "label-class" %>
          <%= f.text_field :first_token, class: "form-control" %>
          
          <%= f.label :app_id, class: "label-class" %>
          <%= f.number_field :app_id, class: "form-control" %>
          
          <%= f.label :app_secret, class: "label-class" %>
          <%= f.text_field :app_secret, class: "form-control" %>
          
          <%= f.label :media_count, class: "label-class" %>
          <%= f.number_field :media_count, class: "form-control" %>
          
          <%= f.submit "データを取得", class: "instagram-btn" %>
        <% end %>
        <% end %>
        </li>
      </ul>
    </li>
  </div>
    
    
  <div class="menu-list">
    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <div>コンテンツを追加</div>
    </a>
    <ul class="dropdown-menu">
      <li>
        <% if @user.id == current_user.id %> <!-- ログイン中のユーザーだった場合  -->
        <h2>※画像か動画、どちらか1つを選択し投稿してください。</h2><hr>
        <!-- マイページに写真、動画を追加する -->
        
          <%= form_with(model: @url, url: user_add_mypage_content_create_path(@user.id), local: true) do |f| %>
              
              <%= f.label :mypage_image %><br>
              <%= f.file_field :mypage_image %><br>
              
              <%= f.label :mypage_movie %><br>
              <%= f.file_field :mypage_movie %><br>
              
              <%= f.submit "投稿する" %>
          <% end %> 
        <% end %>
       </li>
    </ul>
  </li>
  </div>
  
  <!-- 記事の管理 -->
  <div class="menu-list">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <div>記事管理</div>
      </a>
        <ul class="dropdown-menu">
          <li>
           
           　<strong>記事リスト</strong><hr>
           　 <% @user.posts.each do |post| %>
             　<% if @user.id == current_user.id %> <!-- ログイン中のユーザーだった場合  -->
             　   <%= link_to "#{post.title}", edit_posts_path(@user, post) %><hr>
             <% else %>
                 <%= link_to "#{post.title}", confirm_posts_path(@user, post) %><hr>
               <% end %>
             <% end %>
          </li>  
        </ul>
    </li>
  </div>
  
  
  
  
  
  
  <!-- お気に入り -->
  <div class="menu-list">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <div>お気に入り</div>
      </a>
        <ul class="dropdown-menu">
          <li>
            <% if @user.id == current_user.id %> <!-- ログイン中のユーザーだった場合  -->
              <strong>登録リスト</strong><br><hr>
              <% if @favorite_users_id.present? %>
                <% @favorite_users_id.each do |id| %>
                  
                  <span>
                    <%= image_tag User.find(id).image, :size => "30x30" %><%= link_to "#{User.find(id).name}さん", edit_mypage_path(User.find(id)) %>
                    <%= link_to "　解除", user_destroy_path(current_user, User.find(id)), method: :delete, data: { confirm: 'お気に入りを解除しますか?' } %>
                  </span>
                  <hr>
          
                <% end %>
              <% end %> <!-- if @favorite_users_id.present? -->
            <% else %>
              <%= form_with(model: @favorite, url: user_create_path(current_user, @user), method: :post, local: true) do |f| %>
                <%= f.hidden_field :favorite_user, value: @user.id %>
                <%= f.submit "追加" %>
              <% end %>
      
            <% end %> <!--  if @user.id == current_user.id -->
          </li>  
        </ul>
    </li>
  </div>
    
    
  <div class="menu-list">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <div>メッセージ</div>
      </a>
        <ul class="dropdown-menu">
          <li>      
          <% if @user.id == current_user.id %> <!-- ログイン中のユーザーだった場合  -->
            <strong>履歴</strong><br><hr>
            <% if Message.all.where(room_id: @room_ids).present? %>
              <% @users.each do |user| %>
                <p>
                  <span><%= image_tag User.find(user.user_id).image, :size => "30x30" %><%= link_to "#{user.user.name}", room_path(user.room_id) %>
                        <% if user.user.messages.where(already_read: "未読", room_id: user.room_id).count > 0 %>
                          <span class="already_read">new</span>
                        <% end %>
                  </span>
                </p>
                <hr>
              <% end %>
            <% end %>
          <% else %>
            <% if @isRoom == true %>  <!-- 現在ログイン中のuserが回覧中のuserと共通のroom.idを持っている場合  -->
              <p><a href="/rooms/<%= @roomId %>">メッセージ</a>
            <% else %>  <!-- 現在ログイン中のuserが回覧中のuserと共通のroom.idを持っていなかった場合  -->
              <%= form_for @room do |f| %>
                <%= fields_for @entry do |e| %>
                  <%= e.hidden_field :user_id, value: @user.id %>
                <% end %>
                <%= f.submit "チャットルームへ" %>
              <% end %>
            <% end %>
          <% end %>
          </li>
        </ul>
    </li>
  </div>
    
    
  <div class="menu-list">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <div>足跡</div>
      </a>
        <ul class="dropdown-menu">
          <li>
            <% if @footprints.present? %>
              <% @footprints.each do |footprint| %>
                <span><%= image_tag User.find(footprint).image, :size => "30x30" %><%= link_to "#{User.find(footprint).name}", edit_mypage_path(User.find(footprint).id) %></span><hr>
              <% end %>
            <% end %>
          </li>  
        </ul>
    </li>
  </div>



</div> <!-- ul class = "menu" -->

    
</div>
</div>


<hr>



<div class="container">
  <%= form_with(model: @user, url: user_users_url_path(current_user), method: :patch) do |f| %>
  <ul class="gallery">
  <% if @user.third_token.present? %>
    <% @instagram.each do |test| %> <!-- @instagram = @user.urls.all -->
      <%= f.fields_for "urls[]", test do |instagram| %>
        <li class="aaa">  
          <!-- 現在ログイン中のユーザーが@userと同じなら全て表示--> 
        <% if current_user == @user %>
          <!-- test.users_urlはusers_urlがnilも表記されてしまう(viewには見えないが存在している)　その為users_urlに値が入っているもののみに if test.users_url.include?("mp4") を適用している -->
          <% if !test.users_url.nil? %> 
            <% if test.users_url.include?("mp4") %>
                <div class="tee">
                  <%= video_tag test.users_url, controls: true , :size => "281x281" %>
                </div>
            <% else %>
                <div class="tee">
                  <%= image_tag test.users_url, :size => "281x281" %>
                </div>
            <% end %>
          <% else %>
                <div class="tee">
                  <% if test.mypage_image %>
                    <%= image_tag test.mypage_image, :size => "281x281" %>
                  <% else %>
                    <%= video_tag test.mypage_movie, controls: true , :size => "281x281" %>
                  <% end %>
                </div>
          <% end %>
              <div class="tee-test">
                <%= link_to "記事として投稿", user_posts_path(current_user, date: test.users_url), class: "btn btn-xs btn-primary" %>
                <%= instagram.label "非公開" %>
                <%= instagram.check_box :public_url, {} , "true", "false" %>
                <%= instagram.label "削除" %>
                <%= instagram.check_box :select_content_delete, {} , "true", "false" %>
              </div class="tee-test">
          <!-- public_urlがtrueのコンテンツは表示しない -->
        <% elsif test.public_url == true %>
             
          <!-- public_urlがfalseのコンテンツは表示 -->
        <% else %>
            <% if !test.users_url.nil? %> 
            <% if test.users_url.include?("mp4") %>
                <div class="tee">
                  <%= video_tag test.users_url, controls: true , :size => "281x281" %>
                </div>
            <% else %>
                <div class="tee">
                  <%= image_tag test.users_url, :size => "281x281" %>
                </div>
            <% end %>
          <% else %>
                <div class="tee">
                  <% if test.mypage_image %>
                    <%= image_tag test.mypage_image, :size => "281x281" %>
                  <% else %>
                    <%= video_tag test.mypage_movie, controls: true , :size => "281x281" %>
                  <% end %>
                </div>
          <% end %>
         <% end %>
        </li>
      <% end %>
    <% end %> <!-- @instagram.each do |test| -->
    <% end %> <!-- if @user.third_token.present? -->
  </ul>
  <hr>
  <div class="public-btn">
  <% if current_user == @user %>
 　　 <%= f.submit "公開情報を変更" %>
  <% end %>
  </div>
  <% end %>　
</div>

app/views/users/edit_picture.html.erb
<div class="main users-edit">
  <div class="container">
      <div class="form-body">
        <!-- 次の行からform_tagを使い、編集内容を送信できるようにしましょう(endの忘れに注意です) -->
        <%= form_with(model: @user, url: update_picture_path) do |f| %>
        
        <%= f.label :image %>
　　    <%= f.file_field :image %> 
　　    
　　    <%= f.submit "画像アップロード", class: "btn btn-primary" %>
        <% end %>
      </div>
  </div>
</div>

app/views/users/edit_profile.html.erb
<%= render 'shared/error_messages', object: @user %>

<h1>プロフィール設定</h1>

<div class="center">
  <%= image_tag @user.image, :size => '100x100' %><br>
  <%= link_to "プロフィール画像変更", edit_picture_path(current_user), class: "btn profile-btn" %>
</div>

<%= form_with(model: @user, url: update_profile_path, local: true) do |f| %>
<table class="table table-bordered table-striped profile-table">
  
  <tr>
    <th>名前<span class="required">(必須)</span></th>
    <td><%= f.text_field :name %></td>
  </tr> 
  <tr>
    <th>年齢(必須)</th>
    <td><%= f.number_field :age %></td>
  </tr>
  <tr>
    <th>性別(必須)</th>
    <td><%= f.select :sex, ['男', '女'], {include_blank: '---'}, class: 'sample' %></td>
  </tr>
  <tr>
    <th>都道府県(必須)</th>
    <td><%= f.select :prefecture, User.prefectures.keys, {} %></td>
  </tr>
  <tr>
    <th>使用楽器(必須)</th>
    <td><%= f.select :responsible_part, User.responsible_parts.keys, {} %></td>
  <tr>
    <th>好きな音楽シャンル</th>
    <td><%= f.select :genre, User.genres.keys, {}, include_blank: true %></td>
  </tr>
  <tr>
    <th>好きなアーティスト</th>
    <td><%= f.text_field :favorite_artist %></td>
  </tr>
  <tr>
    <th>自己紹介文(必須)</th>
    <td><%= f.text_area :self_introduction, class: "form-control" %></td>
  </tr>

</table>
<div class="center">
  <%= f.submit "決定", class: "btn btn-lg btn-block profile-btn2" %>
</div>
  <% end %>
  

app/views/users/index.html.erb
<h1>新着投稿</h1>

<div class="col-md-10 col-md-offset-1">
 <%= will_paginate %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>名前</th>
      </tr>
    </thead>
    
    <% @users.each do |user| %>
      <tr>
        <% if logged_in? %>
        <% if current_user.admin? && !current_user?(user) %>
        <td><%= link_to user.name, edit_mypage_path(user) %></td>
        <td class="delete-btn"><%= link_to "削除", user_path(user), method: :delete, data: { confirm: '#{user.name}を削除しますか?' }, class: "btn btn-primary" %></td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<div class="wrapper">
  <div class="column cat1">
    <div class="info">
      <div class="outer">
        <h1 class="home-title">バンドメンバー<br>募集アプリ</h1>
      </div>
    </div>
  </div>
  <div class="column cat2">
    <div class="info">
      <div class="row">
        <div class="col-md-7 col-md-offset-3">
          <div class="form-oya">
          <div class="form-ichi">
            <%= form_with(model: @user, local: true) do |f| %>
              <%= render 'shared/error_messages', object: @user %>
            
              <%= f.label :name, class: "label-class" %>
              <%= f.text_field :name, class: "form-control" %>
            
              <%= f.label :email, class: "label-class" %>
              <%= f.email_field :email, class: "form-control" %>
            
              <%= f.label :password, class: "label-class" %>
              <%= f.password_field :password, class: "form-control" %>
            
              <%= f.label :password_confirmation, class: "label-class" %>
              <%= f.password_field :password_confirmation, class: "form-control" %>
            
              <%= f.submit "新規登録", class: "btn btn-primary btn-block label-class" %>
            <% end %>
          
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>記事タイトル<h1>
<h1><%= @user.name %>, <%= @user.email %></h1>