config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
   # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 
  get 'posts/index'
  
  
  
  get 'users/:id/edit_profile', to: 'users#edit_profile', as: :users_profile # プロフィール設定画面
  patch 'users/:id/update_profile', to: 'users#update_profile', as: :update_profile # プロフィール アップデート
  get 'users/:id/edit_mypage', to: 'users#edit_mypage', as: :edit_mypage # マイページ
  patch 'users/:id/update_mypage', to: 'users#update_mypage', as: :update_mypage # マイページ アップデート
  patch 'users/:id/upload_instagram', to: 'users#upload_instagram', as: :upload_instagram # instagram アップロード
  get 'users/:id/edit_picture', to: 'users#edit_picture', as: :edit_picture # 画像編集
  patch 'users/:id/update_picture', to: 'users#update_picture', as: :update_picture # 画像アップロード
  delete 'users/:id/withdraw', to: 'users#withdraw', as: :withdraw # 退会処理
  
  
  get 'users/:id/posts/:post_id/users_confirm_posts', to: 'posts#users_confirm_posts', as: :confirm_posts #　userの記事を確認するページ
  get 'users/:id/posts/:post_id/users_edit_posts', to: 'posts#users_edit_posts', as: :edit_posts #　記事を編集するページ
  patch 'users/:id/posts/:post_id/users_update_posts', to: 'posts#users_update_posts', as: :update_posts #　記事を更新
  delete 'users/:id/posts/:post_id/users_delete_posts', to: 'posts#users_destroy_posts', as: :delete_posts #　記事を削除
  
  resources :users do
     
    get 'posts/:id/posts_show', to: 'posts#posts_show', as: :posts_show # モーダルウィンドウ
    get 'posts/users_posts', to: 'posts#users_posts', as: :posts #　記事を投稿するページ
    post 'posts/users_create_posts', to: 'posts#users_create_posts', as: :create_posts #　記事を作る
    
    
    get 'urls/add_mypage_content', to: 'urls#add_mypage_content', as: :add_mypage_content # マイページへ写真、動画をアップロードする為のページ
    post 'urls/add_mypage_content_create', to: 'urls#add_mypage_content_create', as: :add_mypage_content_create # マイページへ写真、動画をアップロードする
    
    patch 'urls/:id/users_imaeg_and_video_url', to: 'urls#users_imaeg_and_video_url', as: :users_url
    
    post 'favorite_folders/:id/create', to: 'favorite_folders#create', as: :create
    delete 'favorite_folders/:id/delete', to: 'favorite_folders#destroy', as: :destroy
  end
  
  delete 'rooms/:id/messages/:message_id/message_delete', to: 'messages#destroy', as: :message_delete
  
  resources :messages, only: [:create] do
  end
  
  resources :rooms, only: [:create, :show, :index] do
  end
  
 
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    
    before_action :already_read, only: :show
    
    def create
      @room = Room.create
      @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
      @entry2 = Entry.create(entry_params)
      redirect_to "/rooms/#{@room.id}"
    end
    
    def show
      @room = Room.find(params[:id])
      if Entry.where(user_id: current_user.id, room_id: @room.id).present?
        @messages = @room.messages
        @message = Message.new
        @entries = @room.entries
      else
        redirect_back(fallback_location: root_path)
      end
    end
    
    def destroy
    end
    
    private
    
    def entry_params
      params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id)
    end
    
    def already_read
     @room = Room.find(params[:id])
     if current_user && @room.messages.where.not(user_id: current_user.id).where(already_read: "未読").present?
       @room.messages.update(already_read: "既読")
     end
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/show.html.erb
<h1>チャットルーム</h1>

<h4>参加者</h4>
<% @entries.each do |e| %>
  <h5><strong><a href="/users/<%= e.user.id %>/edit_mypage"><%= e.user.name%>さん</a></strong></h5>
<% end %>

<hr>


<% if @messages.present? %>

  <% @messages.each do |m| %>
  <% if m.user.name == current_user.name %>
  <div class="message-room-flex"> <!-- flex 親要素 -->
        <div class="room-image">
          <%= image_tag m.user.image, :size => "40" %>
        </div>
        <div>                        <!-- flex 画像横のユーザー情報 -->
          <div class="room-user-name">
            <small><strong><%= m.user.name %></a></strong></small>
          </div>
          <div class="message-create">
            <strong><%= m.content %></strong>
          </div>
          <span class="delete-btn"><%= m.already_read %><%= link_to " :削除", message_delete_path(@room, m), method: :delete, data: { confirm: '選択したメッセージを削除しますか?' } %></span>
        </div>  <!-- flex 画像横のユーザー情報 -->
  </div>                       <!-- flex 親要素 end -->
    <hr>
    
    
  <% else %>  <!-- m.user.name == current_user.name -->
  
  
    <div class="message-room-flex-right"> <!-- flex 親要素 -->
        <div class="room-image">
          <%= image_tag m.user.image, :size => "40" %>
        </div>
        <div>                        <!-- flex 画像横のユーザー情報 -->
          <div class="room-user-name">
            <small><strong><%= m.user.name %>さん</a></strong></small>
          </div>
          <div class="message-create">
            <strong><%= m.content %></strong>
          </div>
          
          
          
          <% if m.user.name == current_user.name %>
          <span class="delete-btn"><%= link_to ":削除", message_delete_path(@room, m), method: :delete, data: { confirm: '選択したメッセージを削除しますか?' } %></span>
          <% else %>
          <% end %>
          
        </div>  <!-- flex 画像横のユーザー情報 -->
    </div>                       <!-- flex 親要素 end -->
    <hr>
  
  <% end %>  <!--  m.user.name == current_user.name  -->
  
  
  <% end %> <!-- @messages.each do |m| -->
  
<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>




<%= form_for @message do |f| %>
  <%= f.text_area :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %> <!-- :placeholderはvalueのこと テキスト入力欄に最初から入っている文字のこと -->
  <%= f.hidden_field :room_id, :value => @room.id %>
  <br>
  <%= f.submit "投稿する" %>
<% end %>