config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
   # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 
  get 'posts/index'
  
  
  
  get 'users/:id/edit_profile', to: 'users#edit_profile', as: :users_profile # プロフィール設定画面
  patch 'users/:id/update_profile', to: 'users#update_profile', as: :update_profile # プロフィール アップデート
  get 'users/:id/edit_mypage', to: 'users#edit_mypage', as: :edit_mypage # マイページ
  patch 'users/:id/update_mypage', to: 'users#update_mypage', as: :update_mypage # マイページ アップデート
  patch 'users/:id/upload_instagram', to: 'users#upload_instagram', as: :upload_instagram # instagram アップロード
  get 'users/:id/edit_picture', to: 'users#edit_picture', as: :edit_picture # 画像編集
  patch 'users/:id/update_picture', to: 'users#update_picture', as: :update_picture # 画像アップロード
  delete 'users/:id/withdraw', to: 'users#withdraw', as: :withdraw # 退会処理
  
  
  get 'users/:id/posts/:post_id/users_confirm_posts', to: 'posts#users_confirm_posts', as: :confirm_posts #　userの記事を確認するページ
  get 'users/:id/posts/:post_id/users_edit_posts', to: 'posts#users_edit_posts', as: :edit_posts #　記事を編集するページ
  patch 'users/:id/posts/:post_id/users_update_posts', to: 'posts#users_update_posts', as: :update_posts #　記事を更新
  delete 'users/:id/posts/:post_id/users_delete_posts', to: 'posts#users_destroy_posts', as: :delete_posts #　記事を削除
  
  resources :users do
     
    get 'posts/:id/posts_show', to: 'posts#posts_show', as: :posts_show # モーダルウィンドウ
    get 'posts/users_posts', to: 'posts#users_posts', as: :posts #　記事を投稿するページ
    post 'posts/users_create_posts', to: 'posts#users_create_posts', as: :create_posts #　記事を作る
    
    
    get 'urls/add_mypage_content', to: 'urls#add_mypage_content', as: :add_mypage_content # マイページへ写真、動画をアップロードする為のページ
    post 'urls/add_mypage_content_create', to: 'urls#add_mypage_content_create', as: :add_mypage_content_create # マイページへ写真、動画をアップロードする
    
    patch 'urls/:id/users_imaeg_and_video_url', to: 'urls#users_imaeg_and_video_url', as: :users_url
    
    post 'favorite_folders/:id/create', to: 'favorite_folders#create', as: :create
    delete 'favorite_folders/:id/delete', to: 'favorite_folders#destroy', as: :destroy
  end
  
  delete 'rooms/:id/messages/:message_id/message_delete', to: 'messages#destroy', as: :message_delete
  
  resources :messages, only: [:create] do
  end
  
  resources :rooms, only: [:create, :show, :index] do
  end
  
 
end

app/models/post.rb
class Post < ApplicationRecord
     
    
    default_scope -> { order(created_at: :desc) } 
    
    belongs_to :user
    mount_uploader :video, VideoUploader
    mount_uploader :posts_image, ImageUploader
    
    validates :title, presence: true
    validates :content, presence: true
    
    validates :activity_area, presence: true, on: :users_create_posts
    validates :recruitment_part, presence: true, on: :users_create_posts
    validates :band_genre, presence: true, on: :users_create_posts
    
    before_save :activity_area
    
   
 
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :user_profile_set, only: :users_posts
  before_action :set_user, only: [:posts_show, :users_posts, :users_create_posts]
  before_action :set_post, only: [:posts_show]
  before_action :all, only: [:users_posts, :users_create_posts, :users_edit_posts, :index]
  
  
  def index
   @users = User.paginate(page: params[:page], per_page: 9 )
    # Post.find(7).activity_area.include?("#{params[:q][:posts_activity_area_cont]}".gsub(/[\[\]\"]/, ""))
  
    @search = User.includes(:posts).ransack(params[:q])  #追加
    
  if params[:q].present?
     area_array = Post.all.pluck(:activity_area).select { |item| item.include?("#{params[:q][:posts_activity_area_matches_any]}") }
     part_array = Post.all.pluck(:recruitment_part).select { |item| item.include?("#{params[:q][:posts_recruitment_part_matches_any]}") }
     ganre_array = Post.all.pluck(:band_genre).select { |item| item.include?("#{params[:q][:posts_band_genre_matches_any]}") }
     @posts = Post.all.where(activity_area: area_array).where(recruitment_part: part_array).where(band_genre: ganre_array).paginate(page: params[:page], per_page: 9 )
   
  else
    
     @posts = Post.paginate(page: params[:page], per_page: 9 )
  end
  
  end
  # モーダルウィンドウ
  def posts_show
    @post = Post.find(params["id"])
    @user = User.find(params["user_id"])
  end
  # 記事投稿画面
  def users_posts
    @post = Post.new
    if params[:date]
     @from_mypage_data = Post.new(from_mypage_data: params[:date])
    end
  end
  # 記事を作成
  def users_create_posts
      
      @post = Post.new(user_id: current_user.id, title: post_params[:title], content: post_params[:content], from_mypage_data: post_params[:from_mypage_data], posts_image: post_params[:posts_image], video: post_params[:video],
                       activity_area: post_params[:activity_area], activity_day: post_params[:activity_day], course_of_action: post_params[:course_of_action], recruitment_age: post_params[:recruitment_age], 
                       recruitment_gender: post_params[:recruitment_gender], demosound: post_params[:demosound], public_article: post_params[:public_article], post_age: post_params[:post_age],
                       recruitment_part: post_params[:recruitment_part], band_genre: post_params[:band_genre])
      if @post.save(context: :users_create_posts)
        
        flash[:info] = "記事を作成しました。"
        redirect_to posts_index_url
      else
        render :users_posts
      end
  end
  # 記事の編集ページ
  def users_edit_posts
    @user = User.find(params[:id])
    @post = Post.find(params[:post_id])
  end
  
  def users_update_posts
    @user = User.find(params[:id])
    @post = Post.find(params[:post_id])
    if  @post.update(post_params)
      
      flash[:success] = "記事情報を更新しました。"
      redirect_to edit_mypage_url
    else
      flash[:danger] = "更新できませんでした。"
      render :users_edit_posts
    end
  end
  
  def users_confirm_posts
    @user = User.find(params[:id])
    @post = Post.find(params[:post_id])
  end
  
  def users_destroy_posts
    @user = User.find(params[:id])
    @post = Post.find(params[:post_id])
    @post.destroy
    flash[:info] = "記事を削除しました。"
    redirect_to edit_mypage_url(current_user)
  end
  
  private
  
  def set_user
    @user = User.find(params[:user_id])
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:title, :content, :from_mypage_data, :video, :posts_image, :activity_day, :course_of_action, :recruitment_gender,:demosound, :public_article, :recruitment_age, :post_age,
                                 recruitment_part: [], band_genre: [], activity_area: [])
  end
  
  def update_post_params
    params.require(:user).permit(posts: [:title, :content, :from_mypage_data, :video, :posts_image, :activity_day, :course_of_action, :recruitment_gender,:demosound, :public_article, :recruitment_age, :post_age,
                                 recruitment_part: [], band_genre: [], activity_area: []])
  end
  
  def all
    @part = ["ボーカル","ギター","ベース","ピアノ・キーボード","ドラム","パーカッション","管楽器","弦楽器","作詞作曲・アレンシャー","ダンサー","その他"]
    @ganre = ["ポップス","ロック","ハードロック・ヘヴィメタル","パンク・メロコア","ハードコア","スラッシュメタル・デスメタル",
              "ビジュアル系","ファンク・ブルース","ジャズ・フュージョン","カントリー・フォーク","スカ・ロカビリー","ソウル",
              "ゴスペル・アカペラ","ボサノバ・ラテン","クラシック","ヒップホップ・レゲエ","ハウス・テクノ","アニソン・ボカロ","その他"]
    @area = ["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県",
             "茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県",
             "新潟県","富山県","石川県","福井県","山梨県","長野県",
             "岐阜県","静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県",
             "鳥取県","島根県","岡山県","広島県","山口県","徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県", "沖縄県"]
  end
  
  def user_profile_set
    unless current_user.age.present? && current_user.sex.present? && current_user.self_introduction.present?
      flash[:info] = "プロフィールを設定してください。"
      redirect_to users_profile_url(current_user)
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_posts_show.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    
  
  <div class="split">
    <div class="split-item split-left">
        <div class="split-left__inner">
            <% if @post.from_mypage_data? %>
              <% if "mp4".in?(@post.from_mypage_data) %>
                <div class="video"><%= video_tag @post.from_mypage_data, muted: true, controls: true, :size => "400x420"%></div>
              <% else %>
                <div class="video"><%= image_tag @post.from_mypage_data, :size => "400x420"%></div>
              <% end %>
            <% else %>
              <% if @post.video?  %>
                  <div class="video"><%= video_tag @post.video, muted: true, controls: true , :size => "400x420"%></div>
              <% else %>
                  <div class="video"><%= image_tag @post.posts_image, :size => "400x420"%></div>
              <% end %>
            <% end %>
        </div><!--split-left__inner-->
    </div><!--split-item split-left-->
    <div class="split-item split-right">
        <div class="split-right__inner">
           <div class="modal-user-name">
             <%= image_tag @user.image, size: 35 %><%= link_to "#{@user.name}さん(#{@user.prefecture},#{@user.age}歳,#{@user.sex})", edit_mypage_path(@user) %>
           </div>
           <div class="modal-basicinfo">
             
             
             <h5 class="basic-data-tag">[基本データ]</h5>
             <table class="table table-bordered table-striped modal-profile-table">
               <tr>
                 
                 <th class="modal-text">活動日</th>
                 <td class="modal-text-2"><%= @post.activity_day %></td>
                 <th class="modal-text">活動の方向性</th>
                 <td class="modal-text-2"><%= @post.course_of_action %></td>
               </tr>
               
               <tr>
                 <th class="modal-text">募集年齢</th>
                 <td class="modal-text-2"><%= @post.post_age %>~<%= @post.recruitment_age %></td>
                 <th class="modal-text">募集する性別</th>
                 <td class="modal-text-2"><%= @post.recruitment_gender %></td>
               </tr>
               
               <tr>
                 
                 <th class="modal-text">活動地域</th>
                 <td class="modal-text-2", colspan="3"><%= @post.activity_area.gsub(/[\[\]\"]/, "") %></td>
                 
               </tr>
               <tr>
                 <th class="modal-text">募集楽器パート</th>
                 <td class="modal-text-2", colspan="3"><%= @post.recruitment_part.gsub(/[\[\]\"]/, "") %></td>
               </tr>
               <tr>
                 <th class="modal-text">バンドジャンル</th>
                 <td class="modal-text-2", colspan="3"><%= @post.band_genre.gsub(/[\[\]\"]/, "") %></td>
               </tr>
               
             </table>
             
             
             <div class="areticle-content"></div>
               <h5 class="basic-data-tag">[記事内容]</h5>
               <div class="scr">
                 <p>
                   <%= simple_format(@post.content) %>
                 </p>
              </div>
             </div>
             
             
             <h5 class="basic-data-tag">[バンド音源]</h5>
             <div class="demosound">
               <%= raw Rinku.auto_link(h(@post.demosound)) %>
             </div>
             
             <div class="kaka">
               <%= link_to "#{@user.name}さんのページを詳しく見る", edit_mypage_path(@user), class: "btn btn-primary" %>
             </div>
             
             
           </div><!-- modal-basicinfo -->
        </div><!--split-right__inner-->
    </div><!--split-item split-right-->
  </div
    

app/views/posts/index.html.erb
<h2>投稿一覧</h2>

<div class="dropdown">
  <button type="button" id="dropdown1"
      class="btn btn-secondary dropdown-toggle"
      data-toggle="dropdown"
      aria-haspopup="true"
      aria-expanded="false">
      <div class="btn btn-primary">条件検索</div>
  </button>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown1">
    <%= search_form_for(@search, url: posts_index_path)  do |f| %>
    <div class="drop-menu">
      <div class="menu-nakami">活動地域<br><%= f.select :posts_activity_area_matches_any, options_for_select(@area), {include_blank: '指定しない'} %></div><hr>
      <div class="menu-nakami">募集楽器パート<%= f.select :posts_recruitment_part_matches_any, options_for_select(@part), {include_blank: '指定しない'} %></div><hr>
      <div class="menu-nakami">バンドジャンル<%= f.select :posts_band_genre_matches_any, options_for_select(@ganre), {include_blank: '指定しない'} %></div><hr>
      <div class="actions"><%= f.submit "Search" %></div>
    </div>
    <% end %>
  </div>
</div>

<div class="paginate"><%= will_paginate %></div><hr>







            
    

<div class="post-container">
  
  <% @posts.each do |post| %>
    <% user = User.find(post.user_id) %>
      <% if user.admin? %>
      <% else %>
      <div class="post-item-video">
        <% if post.public_article == true %>
          <% if post.from_mypage_data? %>
            <% if "mp4".in?(post.from_mypage_data) %>
              <div class="video"><%= video_tag post.from_mypage_data, muted: true, controls: true , :size => "350x260"%></div>
            <% else %>
              <div class="video"><%= image_tag post.from_mypage_data, :size => "350x260"%></div>
            <% end %>
          <% else %>
            <% if post.video?  %>
                <div class="video"><%= video_tag post.video, muted: true, controls: true , :size => "350x260"%></div>
            <% else %>
                <div class="video"><%= image_tag post.posts_image, :size => "350x260"%></div>
            <% end %>
          <% end %>
          
          
        <div class="post-info">
          <div class="user-syasinn">
            <%= image_tag user.image, :size => '50x50' %>
          </div>
          <div class="user-test">
              <div><%= link_to post.title, user_posts_show_path(user, post.id), remote: true, class: "" %></div>
              <div><%= user.name %>(<%= user.prefecture %>,<%= user.age %><%= user.sex %>)</div>
              <div>投稿時間:<%= post.updated_at.in_time_zone('Tokyo').strftime("%Y/%-m/%-d %-H時%-M分") %></div>
          </div>
        </div>
      </div> <!-- flex-item-video -->
    
      
      
      
      
      
      <% end %>
        <% end %> <!-- post.public_article == true -->
  <% end %>
</div>



<!--モーダルウインドウ表示-->
<div id="posts-show" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/posts/posts_show.js.erb
$("#posts-show").html("<%= escape_javascript(render 'posts_show') %>");
$("#posts-show").modal("show");

app/views/posts/users_confirm_posts.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    
  

    
  
  <div class="split">
    <div class="split-item split-left">
        <div class="split-left__inner">
            <% if @post.from_mypage_data? %>
              <% if "mp4".in?(@post.from_mypage_data) %>
                <div class="video"><%= video_tag @post.from_mypage_data, muted: true, controls: true, :size => "400x420"%></div>
              <% else %>
                <div class="video"><%= image_tag @post.from_mypage_data, :size => "400x420"%></div>
              <% end %>
            <% else %>
              <% if @post.video?  %>
                  <div class="video"><%= video_tag @post.video, muted: true, controls: true , :size => "400x420"%></div>
              <% else %>
                  <div class="video"><%= image_tag @post.posts_image, :size => "400x420"%></div>
              <% end %>
            <% end %>
        </div><!--split-left__inner-->
    </div><!--split-item split-left-->
    <div class="split-item split-right">
        <div class="split-right__inner">
           <div class="modal-user-name">
             <%= image_tag @user.image, size: 35 %><%= link_to "#{@user.name}#{@user.prefecture}#{@user.age}#{@user.sex}", edit_mypage_path(@user) %>
             
           </div>
           <div class="modal-basicinfo">
             
             
             <h5 class="basic-data-tag">[基本データ]</h5>
             <table class="table table-bordered table-striped modal-profile-table">
               <tr>
                 
                 <th class="modal-text">活動日</th>
                 <td class="modal-text-2"><%= @post.activity_day %></td>
                 <th class="modal-text">活動の方向性</th>
                 <td class="modal-text-2"><%= @post.course_of_action %></td>
               </tr>
               
               <tr>
                 <th class="modal-text">募集年齢</th>
                 <td class="modal-text-2"><%= @post.post_age %>~<%= @post.recruitment_age %></td>
                 <th class="modal-text">募集する性別</th>
                 <td class="modal-text-2"><%= @post.recruitment_gender %></td>
               </tr>
               
               <tr>
                 
                 <th class="modal-text">活動地域</th>
                 <td class="modal-text-2", colspan="3"><%= @post.activity_area.gsub(/[\[\]\"]/, "") %></td>
                 
               </tr>
               <tr>
                 <th class="modal-text">募集楽器パート</th>
                 <td class="modal-text-2", colspan="3"><%= @post.recruitment_part.gsub(/[\[\]\"]/, "") %></td>
               </tr>
               <tr>
                 <th class="modal-text">バンドジャンル</th>
                 <td class="modal-text-2", colspan="3"><%= @post.band_genre.gsub(/[\[\]\"]/, "") %></td>
               </tr>
               
             </table>
             
             
             <div class="areticle-content"></div>
               <h5 class="basic-data-tag">[記事内容]</h5>
               <div class="scr">
                 <p>
                   <%= simple_format(@post.content) %>
                 </p>
              </div>
             </div>
             
             
             <h5 class="basic-data-tag">[バンド音源]</h5>
             <div class="demosound">
               <%= raw Rinku.auto_link(h(@post.demosound)) %>
             </div>
             
             <div class="kaka">
              
             </div>
            
             
           </div><!-- modal-basicinfo -->
        </div><!--split-right__inner-->
    </div><!--split-item split-right-->
  </div
    

app/views/posts/users_edit_posts.html.erb
<h1>記事編集</h1>

<%= form_with(model: @post, url: update_posts_path(@user, @post), method: :patch, local: true) do |f| %>

  <table class="table table-bordered table-striped profile-table">
    
    <tr>
      <th class="users-posts-table">
        <%= f.label "記事の公開、非公開" %>
        <div>※公開する場合はチェックボックスにサインしてください</div>
      </th>
      <td>
        <span>公開する</span><%= f.check_box :public_article, class: "form-control" %>
      </td>
    <tr>
      
    <tr>
      <th class="users-posts-table"><%= f.label "記事タイトル" %></th>
      <td><%= f.text_field :title, class: "form-control" %></td>
    </tr>
    
    <tr>
      <th class="users-posts-table"><%= f.label "記事内容(必須)" %></th><br>
      <td><%= f.text_area :content, class: "form-control" %></td>
    </tr>
    
    <tr>
    <% if @post.from_mypage_data.present? %>
      <th class="users-posts-table"><%= f.label "インスタグラムから" %></th>
      <td><%= f.text_area :from_mypage_data, value: @post.from_mypage_data %></td>
    <% end %>
    </tr>
    
    <tr>
    <% if @post.posts_image.present? %>
      <th class="users-posts-table"><%= f.label "画像ファイル" %><div>※画像か動画、どちらかを選択してください。</div></th>
      <td><%= f.file_field :posts_image %></td>
    <% end %>
    </tr>
    
    <tr>
    <% if @post.video.present? %>
      <th class="users-posts-table"><%= f.label "動画ファイル" %><div>※画像か動画、どちらかを選択してください。</div></th>
      <td><%= f.file_field :video %></td>
    <% end %>
    </tr>
    <tr>
      <th class="users-posts-table">活動地域(必須:複数可)</th>
      <td><% @area.each do |area| %>
      <%= area %><%= f.check_box :activity_area, {multiple: true}, area, nil %>
      <% end %></td>
    </tr>
    
    <tr>
      <th class="users-posts-table">募集楽器パート(必須:複数可)</th>
      <td><% @part.each do |part| %>
      <%= part %><%= f.check_box :recruitment_part, {multiple: true}, part, nil %>
      <% end %></td>
    <tr>
    <tr>
      <th class="users-posts-table">バンドジャンル(必須:複数可)</th>
      <td><% @ganre.each do |ganre| %>
      <%= ganre %><%= f.check_box :band_genre, {multiple: true}, ganre, nil %>
      <% end %></td>
    <tr>
    <tr>
      <th class="users-posts-table">活動曜日(任意)</th>
      <td><%= f.select :activity_day, ['指定なし', '平日', '土日', '土曜日', '日曜日'] %></td>
    <tr>
    <tr>
      <th class="users-posts-table">活動の方向性(任意)</th>
      <td><%= f.select :course_of_action,  ['指定なし', 'プロ思考', 'インディーズ', '趣味'] %></td>
    <tr>
    <tr>
      <th class="users-posts-table">募集する性別(任意)</th>
      <td><%= f.select :recruitment_gender,  ['指定なし', '男', '女'] %></td>
    <tr>
    <tr>
      <th class="users-posts-table">募集する年齢(任意)</th>
      <td><%= f.number_field :post_age %>~<%= f.number_field :recruitment_age %></td>
    <tr>
    <tr>
      <th class="users-posts-table">バンド音源(任意)</th>
      <td><%= f.text_field :demosound, class: "form-control" %></td>
    <tr>
    
    
   
  </table>
  <%= f.submit "編集", class: "btn btn-primary" %>
  <%= link_to "削除", delete_posts_path(@user, @post), method: :delete, data: { confirm: "削除してよろしいですか？" }, class: "btn btn-primary" %>

<% end %> 

app/views/posts/users_posts.html.erb
<h1>記事作成</h1><hr>
<%= render 'shared/post_error_messages', object: @user %>

<%= form_with(model: @post, url: user_create_posts_path, local: true) do |f| %>
  <table class="table table-bordered table-striped profile-table">
    <%= render 'shared/error_messages' %>
    
    <tr>
      <th class="users-posts-table">
        <%= f.label "記事の公開、非公開" %>
        <div>※公開する場合はチェックボックスにサインしてください</div>
      </th>
      <td>
        <span>公開する</span><%= f.check_box :public_article, class: "form-control" %>

      </td>
    <tr>
    
    
    <tr>
      <th class="users-posts-table"><%= f.label "記事タイトル" %></th>
      <td><%= f.text_field :title, class: "form-control" %></td>
    </tr>
    
    <tr>
      <th class="users-posts-table"><%= f.label "記事内容(必須)" %></th><br>
      <td><%= f.text_area :content, class: "form-control" %></td>
    </tr>
    
    <tr>
    <% if params[:date] %>
      <th class="users-posts-table"><%= f.label "インスタグラムから" %></th>
      <td><%= f.text_area :from_mypage_data, value: @from_mypage_data.from_mypage_data, readonly: true %></td>
    <% end %>
    </tr>
    
    <tr>
    <% unless params[:date]  %>
      <th class="users-posts-table"><%= f.label "画像ファイル" %><div>※画像か動画、どちらかを選択してください。</div></th>
      <td><%= f.file_field :posts_image %></td>
    <% end %>
    </tr>
    
    <tr>
    <% unless params[:date]  %>
      <th class="users-posts-table"><%= f.label "動画ファイル" %><div>※画像か動画、どちらかを選択してください。</div></th>
      <td><%= f.file_field :video %></td>
    <% end %>
    </tr>
    <tr>
      <th class="users-posts-table">活動地域(必須:複数可)</th>
      <td><% @area.each do |area| %>
      <%= area %><%= f.check_box :activity_area, {multiple: true}, area, nil %>
      <% end %></td>
    </tr>
    
    <tr>
      <th class="users-posts-table">募集楽器パート(必須:複数可)</th>
      <td><% @part.each do |part| %>
      <%= part %><%= f.check_box :recruitment_part, {multiple: true}, part, nil %>
      <% end %></td>
    <tr>
    <tr>
      <th class="users-posts-table">バンドジャンル(必須:複数可)</th>
      <td><% @ganre.each do |ganre| %>
      <%= ganre %><%= f.check_box :band_genre, {multiple: true}, ganre, nil %>
      <% end %></td>
    <tr>
    <tr>
      <th class="users-posts-table">活動曜日(任意)</th>
      <td><%= f.select :activity_day, ['指定なし', '平日', '土日', '土曜日', '日曜日'] %></td>
    <tr>
    <tr>
      <th class="users-posts-table">活動の方向性(任意)</th>
      <td><%= f.select :course_of_action,  ['指定なし', 'プロ思考', 'インディーズ', '趣味'] %></td>
    <tr>
    <tr>
      <th class="users-posts-table">募集する性別(任意)</th>
      <td><%= f.select :recruitment_gender,  ['指定なし', '男', '女'] %></td>
    <tr>
    <tr>
      <th class="users-posts-table">募集する年齢(任意)</th>
      <td><%= f.number_field :post_age %>~<%= f.number_field :recruitment_age %></td>
    <tr>
    <tr>
      <th class="users-posts-table">バンド音源(任意)</th>
      <td><%= f.text_field :demosound, class: "form-control" %></td>
    <tr>
    
  </table>
  <%= f.submit "投稿する" %>
<% end %> 